export type DetailCopy = ReturnType<typeof getDetailCopy>;

export function getDetailCopy(language: "en" | "zh") {
  if (language === "zh") {
    return {
      actionCommandSubtitle: "把推荐动作、优先级和截止节奏放到同一处，减少来回切换。",
      actionCommandTitle: "行动指挥台",
      actionDeadline: "建议节奏",
      actionPrimary: "当前最该做",
      actionStepFollowUp: "推进 / 跟进",
      actionStepResume: "简历动作",
      actionStepSkill: "技能动作",
      actions: "行动建议",
      applicationSnapshot: "申请快照",
      areasToImprove: "需要补强",
      currentState: "当前状态",
      decisionBrief: "决策摘要",
      decisionBriefHelper: "下一步可以先看行动计划；如果准备投递，先进入简历匹配把摘要和项目要点对齐。",
      decisionRationale: "判断依据",
      decisionStage: "决策阶段",
      focusAreasHelper: "下一步重点",
      fullAnalysisSummary: "查看完整分析摘要",
      gapSkills: "待补缺口",
      interviewBoardSubtitle: "把优势、风险、STAR 证据和反问点提前整理好。",
      interviewBoardTitle: "面试作战板",
      interviewFocus: "面试准备重点",
      interviewNoteBody:
        "这些问题来自当前分析中的优势、短板和岗位要求，不是外部面试题库。",
      interviewNoteTitle: "说明",
      interviewProofLabel: "证明优势",
      interviewProofTitle: "开场可讲的强信号",
      interviewQuestionFallback: "准备一个关于岗位成功标准、团队协作或前 90 天重点的反问。",
      interviewQuestionLabel: "反问准备",
      interviewQuestionTitle: "需要问清楚",
      interviewRiskLabel: "风险预演",
      interviewRiskTitle: "可能被追问的短板",
      interviewStoryFallback: "准备一个包含场景、行动、结果的 STAR 案例。",
      interviewStoryLabel: "STAR 素材",
      interviewStoryTitle: "把要求转成故事",
      jobOverview: "岗位概览",
      jobOverviewSubtitle: "来自当前保存的职位分析。",
      mainRisk: "主要风险",
      match: "匹配度",
      noActionDetail: "暂无更具体的行动说明。",
      noMissingSkillDetails: "暂无详细技能缺口",
      noMissingSkillDetailsBody: "当前分析没有提供可拆分的技能缺口详情。",
      noPriorityGap: "暂无高优先级缺口",
      noPriorityGapBody: "当前技能覆盖较完整，下一步可以把已有技能证据写得更具体。",
      noSignalYet: "当前分析暂未提供该信号。",
      noSimilarRoles: "暂无相似机会",
      noSimilarRolesBody: "当 tracker 中存在同类型或技能重叠岗位时会显示在这里。",
      noSummary: "暂无 AI 总结。",
      overviewSubtitle: "用当前分析字段生成的职位匹配摘要。",
      overviewTitle: "概览",
      overviewDecisionSubtitle: "匹配度、阶段、截止日期和申请渠道集中在一个决策面板里。",
      overviewDecisionTitle: "机会健康度",
      provenSkills: "已证明技能",
      reportHealth: "报告完整度",
      reportTabs: "报告分页",
      resumeFocus: "准备材料",
      resumeFitSignals: "简历匹配信号",
      resumeKeywordsHelper: "可用于简历优化",
      resumeSignal: "简历信号",
      riskReview: "风险复盘",
      roleKeywords: "岗位关键词",
      salary: "薪资",
      similarRoles: "相关机会",
      similarRolesSubtitle: "仅使用你已保存的本地/云端职位。",
      skillCoachSubtitle: "先看哪个缺口最影响匹配，再决定是写进简历、补项目，还是暂时降优先级。",
      skillCoachTitle: "技能诊断",
      skillCoverage: "技能覆盖",
      skillEvidenceBody: "这些词适合优先写进 Summary 或项目 bullet，作为技能证据。",
      skillEvidenceTitle: "可写进简历的证据",
      skillPriorityFix: "优先补强",
      skillSignalsSubtitle: "把分散的技能、工具和关键词集中展示，减少来回扫卡片。",
      skillSignalsTitle: "技能信号板",
      skillsSubtitle: "基于 JD 证据和已有分析分数，不虚构新百分比。",
      strongestSignal: "推进理由",
      subtitle: "先决定是否推进，再查看完整分析证据。",
      tailorResume: "定制简历",
      tailoringAdviceHelper: "可执行建议",
      title: "职位决策",
      topEvidence: "最强证据",
      updated: "更新于",
      viewActionPlan: "查看行动计划",
      watchOut: "需要确认",
      weakestSignal: "最弱维度",
      yourAdvantages: "你的优势",
      tabs: {
        actions: "行动",
        interview: "面试准备",
        overview: "概览",
        resume: "简历匹配",
        skills: "技能"
      }
    };
  }

  return {
    actionCommandSubtitle: "Keep the recommended move, priority, and timing in one place.",
    actionCommandTitle: "Action command center",
    actionDeadline: "Suggested timing",
    actionPrimary: "Do this now",
    actionStepFollowUp: "Advance / follow up",
    actionStepResume: "Resume move",
    actionStepSkill: "Skill move",
    actions: "Recommended actions",
    applicationSnapshot: "Application snapshot",
    areasToImprove: "Areas to improve",
    currentState: "Current state",
    decisionBrief: "Decision brief",
    decisionBriefHelper: "Start with the action plan. If this role is worth moving, tailor the resume summary and project bullets next.",
    decisionRationale: "Decision rationale",
    decisionStage: "Decision stage",
    focusAreasHelper: "Next-step focus",
    fullAnalysisSummary: "View full analysis summary",
    gapSkills: "Gap skills",
    interviewBoardSubtitle: "Prepare strengths, risks, STAR evidence, and questions before the call.",
    interviewBoardTitle: "Interview command board",
    interviewFocus: "Interview prep focus",
    interviewNoteBody:
      "These prompts are derived from the current analysis strengths, gaps, and role requirements. No external interview dataset is used.",
    interviewNoteTitle: "Note",
    interviewProofLabel: "Proof",
    interviewProofTitle: "Strong signal to open with",
    interviewQuestionFallback: "Prepare one question about success criteria, team collaboration, or the first 90 days.",
    interviewQuestionLabel: "Questions",
    interviewQuestionTitle: "Clarify this",
    interviewRiskLabel: "Risk rehearsal",
    interviewRiskTitle: "Likely follow-up gap",
    interviewStoryFallback: "Prepare one STAR story with situation, action, and result.",
    interviewStoryLabel: "STAR material",
    interviewStoryTitle: "Turn requirements into a story",
    jobOverview: "Job overview",
    jobOverviewSubtitle: "From the saved analysis for this role.",
    mainRisk: "Main risk",
    match: "Match",
    noActionDetail: "No more specific action detail is available.",
    noMissingSkillDetails: "No detailed gaps",
    noMissingSkillDetailsBody: "This analysis does not include separate missing skill details.",
    noPriorityGap: "No high-priority gap",
    noPriorityGapBody: "Skill coverage looks complete enough. Make existing evidence more concrete next.",
    noSignalYet: "No signal provided yet.",
    noSimilarRoles: "No similar roles yet",
    noSimilarRolesBody: "Related opportunities appear when saved jobs share role type or skills.",
    noSummary: "No AI summary is available yet.",
    overviewSubtitle: "A decision-ready summary using the current analysis fields.",
    overviewTitle: "Overview",
    overviewDecisionSubtitle: "Match, stage, deadline, and channel are grouped in one decision panel.",
    overviewDecisionTitle: "Opportunity health",
    provenSkills: "Proven skills",
    reportHealth: "Report health",
    reportTabs: "Report sections",
    resumeFocus: "Material to prepare",
    resumeFitSignals: "Resume fit signals",
    resumeKeywordsHelper: "Resume optimization inputs",
    resumeSignal: "Resume signal",
    riskReview: "Risk review",
    roleKeywords: "Role keywords",
    salary: "Salary",
    similarRoles: "Related opportunities",
    similarRolesSubtitle: "Only saved local/cloud jobs are used.",
    skillCoachSubtitle: "See the gap most likely to affect fit, then decide whether to prove it, learn it, or lower priority.",
    skillCoachTitle: "Skill diagnosis",
    skillCoverage: "Skill coverage",
    skillEvidenceBody: "Use these terms first in the summary or project bullets as skill evidence.",
    skillEvidenceTitle: "Resume evidence to reuse",
    skillPriorityFix: "Priority fix",
    skillSignalsSubtitle: "Skills, tools, and keywords are grouped here so the tab is easier to scan.",
    skillSignalsTitle: "Skill signal board",
    skillsSubtitle: "Based on JD evidence and existing analysis scores, without invented percentages.",
    strongestSignal: "Why move",
    subtitle: "Decide whether to move first, then inspect the evidence.",
    tailorResume: "Tailor resume",
    tailoringAdviceHelper: "Actionable guidance",
    title: "Job decision",
    topEvidence: "Top evidence",
    updated: "Updated",
    viewActionPlan: "View action plan",
    watchOut: "Check before moving",
    weakestSignal: "Weakest signal",
    yourAdvantages: "Your advantages",
    tabs: {
      actions: "Actions",
      interview: "Interview Prep",
      overview: "Overview",
      resume: "Resume Fit",
      skills: "Skills"
    }
  };
}

export type ResumeDraftCopy = ReturnType<typeof getResumeDraftCopy>;

export function getResumeDraftCopy(language: "en" | "zh") {
  if (language === "zh") {
    return {
      addNote: "添加修改说明...",
      analyzeAgain: "重新分析",
      applyPolish: "应用 AI 修改",
      bodyLabel: "摘要 / 项目要点",
      cancel: "取消",
      checklistDone: "已完成",
      checklistTitle: "简历匹配检查清单",
      copyError: "复制失败，请手动复制。",
      copied: "已复制",
      copyToClipboard: "复制文本",
      currentVersion: "当前版本",
      downloadDoc: "下载 Word",
      draftTitle: "简历摘要草稿",
      draftTitlePlaceholder: "例：面向运营经理岗位的简历草稿",
      editBody: "编辑摘要文本",
      fallbackTitle: "未命名草稿",
      generateDraft: "生成草稿",
      headerPlaceholder: "例：张三 · 运营经理 · 5年经验",
      highlightMatch: "高亮匹配词",
      improve: "优化",
      instructionLabel: "修改指令",
      instructionPlaceholder: "例：请使用更结果导向的语言...",
      keywordCluster: "关键词集群",
      matchDiagnosticTitle: "匹配诊断",
      matchScore: "匹配分数",
      missingKeywords: "缺失关键词",
      missingKeywordsPlaceholder: "从 JD 复制关键词，或让 AI 自动填充...",
      notesLabel: "额外说明",
      notesPlaceholder: "补充说明你想让 AI 知道的...",
      polishError: "优化失败，请重试。",
      polishTitle: "AI 简历优化",
      polishing: "优化中...",
      previewTitle: "简历预览",
      readyStatus: "准备状态",
      regenerate: "重新生成",
      resumePreviewDescription: "使用当前岗位的 AI 分析信号构建的简历草稿。",
      resumeTitle: "简历匹配",
      saveDraft: "保存草稿",
      saved: "已保存",
      saving: "保存中...",
      scoreLabel: "匹配分数",
      searchKeywords: "搜索关键词...",
      skillsCovered: "技能覆盖",
      summaryLabel: "摘要",
      tabs: {
        draft: "草稿",
        preview: "预览"
      },
      versionSaved: "版本已保存。",
      // Additional resume draft properties
      aiPolish: "AI 优化",
      bullets: "项目要点",
      bulletsHelper: "每行一个项目要点",
      checklistBullets: "项目要点",
      checklistKeywords: "关键词",
      checklistReady: "准备就绪",
      checklistSummary: "摘要",
      copy: "复制",
      copyInsert: "插入到草稿",
      coveredKeywords: "已覆盖关键词",
      draftReady: "草稿已准备",
      draftSaved: "草稿已保存",
      evidenceStrength: "证据强度",
      firstFixGeneric: "优化匹配度",
      firstFixGenericDetail: "根据分析建议调整简历重点。",
      firstFixKeyword: (keyword: string) => `优先覆盖"${keyword}"`,
      firstFixKeywordDetail: "把这个关键词自然地写进简历。",
      firstFixSkill: (skill: string) => `优先补强"${skill}"`,
      firstFixTitle: "优先修复",
      keywordCoverage: "关键词覆盖",
      keywordsHelper: "来自岗位分析的关键词",
      manualCopyHelper: "如果自动复制失败，请手动选择文本复制。",
      markReviewed: "标记已复核",
      matchDiagnosticSubtitle: "关键词覆盖和技能匹配快照",
      needsWork: "需改进",
      noCoveredKeywords: "暂无覆盖关键词",
      noMissingKeywords: "暂无缺失关键词",
      optionalFieldsSubtitle: "补充信息让 AI 输出更精准",
      optionalFieldsTitle: "补充字段",
      packageCompany: "公司",
      packageKeywords: "关键词",
      packageLabel: "简历草稿包",
      packageRole: "岗位",
      polishApplied: "已应用 AI 优化",
      polishApply: "应用修改",
      polishCancel: "取消",
      polishCloseLabel: "关闭 AI 简历优化",
      polishCurrent: "当前草稿",
      polishDiffAdded: "新增",
      polishDiffRemoved: "删除",
      polishFailed: "优化失败",
      polishGenerate: "生成优化建议",
      polishGenerating: "正在生成...",
      polishInstructionLabel: "优化指令",
      polishInstructionPlaceholder: "例：让语言更结果导向...",
      polishNoResult: "未返回优化结果",
      polishResultTitle: "优化结果",
      polishSafetyNote: "AI 生成内容，请复核后再使用。",
      polishSubtitle: "让 AI 帮你润色草稿",
      polishSuggestion: "建议修改",
      previewBullets: "项目要点",
      previewDensity: "简历密度",
      previewEmpty: "（空）",
      previewEstimatedLines: "行",
      previewEyebrow: "简历草稿",
      previewGuardrails: "注意事项",
      previewKeywords: "关键词",
      previewLong: "偏长",
      previewLongHelper: "简历密度偏高，建议精简部分内容。",
      previewReady: "准备就绪",
      previewReadyHelper: "简历密度适中，可以直接投递。",
      previewSubtitle: "基于岗位分析生成的草稿预览",
      previewSummary: "摘要",
      previewTight: "适中",
      previewTightHelper: "简历密度合理，可以继续优化细节。",
      ready: "就绪",
      reviewed: "已复核",
      reviewedSaved: "已保存并标记复核",
      risks: "风险提示",
      risksHelper: "每行一条风险提示",
      skillCoverage: "技能覆盖",
      subtitle: "定制简历",
      summary: "摘要",
      title: "简历匹配",
    };
  }

  return {
    addNote: "Add a note...",
    analyzeAgain: "Analyze again",
    applyPolish: "Apply AI edits",
    bodyLabel: "Summary / project bullets",
    cancel: "Cancel",
    checklistDone: "Done",
    checklistTitle: "Resume fit checklist",
    copyError: "Copy failed. Please copy manually.",
    copied: "Copied",
    copyToClipboard: "Copy text",
    currentVersion: "Current version",
    downloadDoc: "Download Word",
    draftTitle: "Resume summary draft",
    draftTitlePlaceholder: "e.g. Resume draft for Operations Manager",
    editBody: "Edit summary text",
    fallbackTitle: "Untitled draft",
    generateDraft: "Generate draft",
    headerPlaceholder: "e.g. John Doe · Operations Manager · 5 yrs",
    highlightMatch: "Highlight match",
    improve: "Improve",
    instructionLabel: "Edit instruction",
    instructionPlaceholder: "e.g. Use more result-oriented language...",
    keywordCluster: "Keyword cluster",
    matchDiagnosticTitle: "Match diagnostic",
    matchScore: "Match score",
    missingKeywords: "Missing keywords",
    missingKeywordsPlaceholder: "Paste keywords from JD, or let AI auto-fill...",
    notesLabel: "Additional notes",
    notesPlaceholder: "Anything else you want the AI to know...",
    polishError: "Polish failed. Please try again.",
    polishTitle: "AI resume polish",
    polishing: "Polishing...",
    previewTitle: "Resume preview",
    readyStatus: "Readiness",
    regenerate: "Regenerate",
    resumePreviewDescription: "A resume draft built from the current job analysis signals.",
    resumeTitle: "Resume fit",
    saveDraft: "Save draft",
    saved: "Saved",
    saving: "Saving...",
    scoreLabel: "Match score",
    searchKeywords: "Search keywords...",
    skillsCovered: "Skills covered",
    summaryLabel: "Summary",
    tabs: {
      draft: "Draft",
      preview: "Preview"
    },
    versionSaved: "Version saved.",
    // Additional resume draft properties
    aiPolish: "AI Polish",
    bullets: "Project bullets",
    bulletsHelper: "One bullet per line",
    checklistBullets: "Bullets",
    checklistKeywords: "Keywords",
    checklistReady: "Ready",
    checklistSummary: "Summary",
    copy: "Copy",
    copyInsert: "Insert into draft",
    coveredKeywords: "Covered keywords",
    draftReady: "Draft ready",
    draftSaved: "Draft saved",
    evidenceStrength: "Evidence strength",
    firstFixGeneric: "Improve match",
    firstFixGenericDetail: "Adjust resume focus based on analysis.",
    firstFixKeyword: (keyword: string) => `Cover "${keyword}" first`,
    firstFixKeywordDetail: "Naturally include this keyword in your resume.",
    firstFixSkill: (skill: string) => `Prioritize "${skill}"`,
    firstFixTitle: "Priority fix",
    keywordCoverage: "Keyword coverage",
    keywordsHelper: "Keywords from job analysis",
    manualCopyHelper: "If auto-copy fails, select and copy text manually.",
    markReviewed: "Mark reviewed",
    matchDiagnosticSubtitle: "Keyword coverage and skill match snapshot",
    needsWork: "Needs work",
    noCoveredKeywords: "No covered keywords",
    noMissingKeywords: "No missing keywords",
    optionalFieldsSubtitle: "Extra context for better AI output",
    optionalFieldsTitle: "Optional fields",
    packageCompany: "Company",
    packageKeywords: "Keywords",
    packageLabel: "Resume draft package",
    packageRole: "Role",
    polishApplied: "AI polish applied",
    polishApply: "Apply edits",
    polishCancel: "Cancel",
    polishCloseLabel: "Close AI resume polish",
    polishCurrent: "Current draft",
    polishDiffAdded: "Added",
    polishDiffRemoved: "Removed",
    polishFailed: "Polish failed",
    polishGenerate: "Generate polish",
    polishGenerating: "Generating...",
    polishInstructionLabel: "Polish instruction",
    polishInstructionPlaceholder: "e.g. Use more result-oriented language...",
    polishNoResult: "No polish result returned",
    polishResultTitle: "Polish result",
    polishSafetyNote: "AI-generated content. Review before using.",
    polishSubtitle: "Let AI polish your draft",
    polishSuggestion: "Suggested edit",
    previewBullets: "Project bullets",
    previewDensity: "Resume density",
    previewEmpty: "(empty)",
    previewEstimatedLines: "lines",
    previewEyebrow: "Resume draft",
    previewGuardrails: "Guardrails",
    previewKeywords: "Keywords",
    previewLong: "Long",
    previewLongHelper: "Resume density is high. Consider trimming some content.",
    previewReady: "Ready",
    previewReadyHelper: "Resume density is optimal. Ready to apply.",
    previewSubtitle: "Draft preview built from job analysis",
    previewSummary: "Summary",
    previewTight: "Tight",
    previewTightHelper: "Resume density is reasonable. Keep refining details.",
    ready: "Ready",
    reviewed: "Reviewed",
    reviewedSaved: "Saved & marked reviewed",
    risks: "Risk notes",
    risksHelper: "One risk note per line",
    skillCoverage: "Skill coverage",
    subtitle: "Tailor resume",
    summary: "Summary",
    title: "Resume fit",
  };
}
