export type WorkspaceCopy = ReturnType<typeof getWorkspaceCopy>;

export function getWorkspaceCopy(language: "en" | "zh") {
  if (language === "zh") {
    return {
      actionQueueSubtitle: "按当前最需要处理的求职动作组织 tracker。",
      actionQueueTitle: "行动队列",
      actionStage: "行动阶段",
      activePipeline: "正在推进的机会",
      aiWorkspace: "AI 分析",
      actNow: "立即行动",
      analysisSavedToTracker: "分析完成，已在机会追踪器中新建记录。点击「打开详情」查看完整 AI 报告。",
      analyzeActionDescription: "粘贴 JD 并生成匹配度、风险和下一步建议。",
      averageAcrossRoles: "基于已保存分析",
      allStages: "全部阶段",
      allStageSummary: (count: number) => `正在显示全部 ${count} 个机会。`,
      captureAndAnalyze: "导入新机会",
      clearStageFilter: "清除阶段筛选",
      commandEyebrow: "求职工作台",
      commandSubtitle: "收集职位、生成分析、改简历和跟进投递分别进入专门页面；工作台只负责帮你决定今天该推进什么。",
      commandTitle: "把机会变成清晰的下一步",
      comingSoon: "即将上线",
      deadlineDue: (date: string) => `申请截止：${date}`,
      emptyStage: "暂无",
      filterStage: "聚焦",
      focusQueue: "聚焦队列",
      followUpToolBody: "集中处理投递后的跟进、面试感谢信和临近截止日期。",
      followUpToolTitle: "跟进投递",
      gapActionDescription: "从现有分析中查看常见短板和优先级。",
      heroSubtitle: "粘贴职位描述，Offerwise 会生成匹配分数、风险、简历重点和下一步建议。",
      heroTitle: "分析下一个值得投入的机会",
      highPriorityBody: (count: number) => `${count} 个高匹配机会值得优先推进。`,
      highPriorityLabel: "优先级",
      highPriorityTitle: "先处理高匹配岗位",
      highMatchTitle: "高匹配",
      importJob: "导入职位",
      importToolBody: "粘贴 JD、保存草稿并运行 AI 分析。",
      importToolTitle: "收集和分析",
      insightsActionDescription: "查看基于已保存职位的匹配、状态和技能趋势。",
      interviewComingSoon: "面试准备尚未有独立页面，暂不创建假入口。",
      inFocus: "聚焦中",
      latestDescription: "基于你最新保存的分析。",
      latestEmptyBody: "完成一次 JD 分析后，这里会显示最新机会。",
      latestEmptyTitle: "还没有分析记录",
      latestTitle: "最新分析",
      marketEmptyBody: "添加或载入职位后，这里会基于你的职位数据总结方向。",
      marketEmptyTitle: "暂无可用洞察",
      marketSubtitle: "只基于你已保存的岗位数据，不使用外部市场数据。",
      marketTitle: "市场线索",
      matchDistributionSubtitle: "基于当前 tracker 内的真实匹配分数。",
      needAction: "需要行动",
      needActionTitle: "待行动",
      nextStep: "下一步",
      nextFocusEmptyBody: "先从 Import Inbox 导入或分析一个职位，Workspace 会自动给出下一步。",
      nextFocusEmptyTitle: "还没有待处理机会",
      nextFocusEyebrow: "下一步焦点",
      nextFocusSubtitle: "按阶段、截止日期和匹配分数选出最值得先处理的机会。",
      nextFocusTitle: "今天先处理这一项",
      noQueueJob: "当前没有职位",
      open: "打开",
      openFollowUp: "打开待跟进",
      openImportInbox: "打开导入收件箱",
      openInsights: "打开洞察",
      openJob: "打开职位",
      openResumeHub: "打开简历中心",
      optimizeResume: "优化候选人画像",
      outcomes: "已记录结果",
      paceBody: (count: number) => `本周新增 ${count} 个机会，保持筛选节奏。`,
      paceLabel: "节奏",
      paceTitle: "持续推进 tracker",
      pathStepOneBody: "粘贴岗位描述或使用示例。",
      pathStepOneLabel: "分析 JD",
      pathStepThreeBody: "保存岗位并跟踪状态。",
      pathStepThreeLabel: "决定下一步",
      pathStepTwoBody: "完善候选人画像可提升评分准确度。",
      pathStepTwoLabel: "校准画像",
      prepareInterview: "准备面试",
      recommendedAction: "推荐行动",
      recentEmptyBody: "分析职位或载入示例数据后会出现最近记录。",
      recentEmptyTitle: "暂无最近分析",
      recentSubtitle: "最近更新的 3 到 5 个机会。",
      recentTitle: "最近分析",
      resumeActionDescription: "更新画像和简历信息，让后续匹配更准确。",
      resumeHubTitle: "简历中心",
      resumeToolBody: "维护候选人画像和简历素材，让后续匹配和定制更准确。",
      resumeToolTitle: "简历资产",
      reportPreview: "AI 摘要",
      reviewSkillGaps: "查看技能差距",
      rolesTracked: "已保存机会",
      skillsEmptyBody: "当分析结果包含 missing skills 时，这里会显示高频缺口。",
      skillsEmptyTitle: "暂无技能缺口",
      skillsSubtitle: "从所有已保存分析的 missing skills 中推导。",
      skillsTitle: "技能进展与缺口",
      skillGapBody: (skill: string) => `${skill} 是当前最常出现的补强点。`,
      skillGapEmptyBody: "完善更多分析后会出现高频技能缺口。",
      skillGapLabel: "技能缺口",
      skillGapTitle: "把短板转成简历重点",
      followUpDue: (date: string) => `跟进日期：${date}`,
      stepOneLabel: "导入",
      stepTwoLabel: "准备",
      stepThreeLabel: "跟进",
      stageFilterSummary: (stage: string, count: number) =>
        `已筛选到「${stage}」阶段，下面显示 ${count} 个匹配机会。`,
      stageCtas: {
        follow_up: "跟进",
        needs_review: "检查",
        parked: "打开",
        ready_to_apply: "投递检查",
        tailor_resume: "改简历"
      },
      stageEmptyHelpers: {
        follow_up: "投递或面试后会进入这里。",
        needs_review: "新的或不确定机会会进入这里。",
        parked: "跳过、拒绝或暂缓的机会会进入这里。",
        ready_to_apply: "简历确认后会进入这里。",
        tailor_resume: "需要改简历的岗位会进入这里。"
      },
      stageHelpers: {
        follow_up: "检查是否需要 follow-up 或面试感谢信。",
        needs_review: "先判断这个机会是否值得投入时间。",
        parked: "低优先级保存，除非匹配度或时间线变化。",
        ready_to_apply: "做最后关键词检查并准备提交。",
        tailor_resume: "先完成定制摘要和项目要点。"
      },
      stages: {
        follow_up: "跟进",
        needs_review: "待判断",
        parked: "暂存",
        ready_to_apply: "可投递",
        tailor_resume: "改简历"
      },
      subtitle: "分析职位、跟踪机会，并规划下一步行动。",
      trackerSubtitle: "保留筛选、批量操作、状态更新、CSV 导出和云同步。",
      trackerTitle: "机会追踪器",
      viewTracker: "查看 tracker",
      workflowGuideToggle: "工作流指引",
      actionQueueToggle: "行动队列",
      activeStages: "活跃阶段"
    };
  }

  return {
    actionQueueSubtitle: "Organize the tracker by the next job-search action.",
    actionQueueTitle: "Action queue",
    actionStage: "Action stage",
    activePipeline: "Active pipeline",
    aiWorkspace: "AI analysis",
    actNow: "Act now",
    analysisSavedToTracker: "Analysis complete. A new tracker record was created. Open details from the list to view the full AI report.",
    analyzeActionDescription: "Paste a JD and generate fit, risks, and next steps.",
    averageAcrossRoles: "Across saved analyses",
    allStages: "All stages",
    allStageSummary: (count: number) => `Showing all ${count} saved opportunities.`,
    captureAndAnalyze: "Import a role",
    clearStageFilter: "Clear stage filter",
    commandEyebrow: "Job search operating desk",
    commandSubtitle: "Collect jobs, run analysis, tailor resumes, and handle follow-ups in dedicated workspaces. Workspace stays focused on what to move next.",
    commandTitle: "Turn saved opportunities into a clear next move",
    comingSoon: "Coming soon",
    deadlineDue: (date: string) => `Deadline: ${date}`,
    emptyStage: "Empty",
    filterStage: "Focus",
    focusQueue: "Focus queue",
    followUpToolBody: "Handle post-application nudges, interview thank-you notes, and near-deadline checks.",
    followUpToolTitle: "Follow up",
    gapActionDescription: "Review repeated gaps and priority areas from saved roles.",
    heroSubtitle: "Paste a job description. Offerwise turns it into fit, risks, resume focus, and the next action.",
    heroTitle: "Analyze the next role worth your time",
    highPriorityBody: (count: number) => `${count} high-match roles are ready to review first.`,
    highPriorityLabel: "Priority",
    highPriorityTitle: "Start with strongest fits",
    highMatchTitle: "High match",
    importJob: "Import job",
    importToolBody: "Paste a JD, save drafts, and run the AI analysis pipeline.",
    importToolTitle: "Collect and analyze",
    insightsActionDescription: "Review match, status, and skill trends from your saved roles.",
    interviewComingSoon: "Interview prep does not have a dedicated route yet, so this is intentionally disabled.",
    inFocus: "In focus",
    latestDescription: "Based on your latest saved analysis.",
    latestEmptyBody: "Run a JD analysis and your newest opportunity will appear here.",
    latestEmptyTitle: "No analysis yet",
    latestTitle: "Latest analysis",
    marketEmptyBody: "Add or load roles to summarize patterns from your own tracker.",
    marketEmptyTitle: "No insights yet",
    marketSubtitle: "Derived only from your saved roles. No external market data is used.",
    marketTitle: "Market signals",
    matchDistributionSubtitle: "Based on real match scores in your tracker.",
    needAction: "need action",
    needActionTitle: "Need action",
    nextStep: "Next step",
    nextFocusEmptyBody: "Import or analyze a role first. Workspace will surface the next item to move.",
    nextFocusEmptyTitle: "No active focus yet",
    nextFocusEyebrow: "Next focus",
    nextFocusSubtitle: "Chosen from action stage, deadline, and match strength.",
    nextFocusTitle: "Start here today",
    noQueueJob: "No roles here",
    open: "Open",
    openFollowUp: "Open Follow Up",
    openImportInbox: "Open Import Inbox",
    openInsights: "Open Insights",
    openJob: "Open job",
    openResumeHub: "Open Resume Hub",
    optimizeResume: "Optimize profile",
    outcomes: "Recorded outcomes",
    paceBody: (count: number) => `${count} saved roles give you enough signal to keep prioritizing.`,
    paceLabel: "Pace",
    paceTitle: "Keep the tracker moving",
    pathStepOneBody: "Paste a JD or load the sample.",
    pathStepOneLabel: "Analyze JD",
    pathStepThreeBody: "Save the role and track status.",
    pathStepThreeLabel: "Decide next step",
    pathStepTwoBody: "Profile quality improves score accuracy.",
    pathStepTwoLabel: "Calibrate profile",
    prepareInterview: "Prepare interview",
    recommendedAction: "Recommended action",
    recentEmptyBody: "Other recently updated opportunities will appear here after the latest highlight.",
    recentEmptyTitle: "No other recent opportunities",
    recentSubtitle: "Excludes the latest opportunity already highlighted above.",
    recentTitle: "Recent opportunities",
    resumeActionDescription: "Update your profile and resume inputs for sharper matching.",
    resumeHubTitle: "Resume Hub",
    resumeToolBody: "Maintain profile and resume assets so matching and tailoring stay accurate.",
    resumeToolTitle: "Resume assets",
    reportPreview: "AI summary",
    reviewSkillGaps: "Review skill gaps",
    rolesTracked: "Saved opportunities",
    skillsEmptyBody: "When analyses include missing skills, repeated gaps will show here.",
    skillsEmptyTitle: "No skill gaps yet",
    skillsSubtitle: "Ranked from saved missing skills. Workspace shows a lightweight preview only.",
    skillsTitle: "Top skill gaps",
    skillGapBody: (skill: string) => `${skill} appears most often across saved gaps.`,
    skillGapEmptyBody: "More analyses will reveal repeated skill gaps.",
    skillGapLabel: "Skill gap",
    skillGapTitle: "Turn gaps into resume focus",
    followUpDue: (date: string) => `Follow-up due: ${date}`,
    stepOneLabel: "Import",
    stepTwoLabel: "Prepare",
    stepThreeLabel: "Follow up",
    stageFilterSummary: (stage: string, count: number) =>
      `Filtered to ${stage}. Showing ${count} matching ${count === 1 ? "opportunity" : "opportunities"} below.`,
    stageCtas: {
      follow_up: "Follow up",
      needs_review: "Review",
      parked: "Open",
      ready_to_apply: "Final check",
      tailor_resume: "Tailor resume"
    },
    stageEmptyHelpers: {
      follow_up: "Applied and interview roles will land here.",
      needs_review: "New or uncertain roles wait here first.",
      parked: "Skipped, rejected, or lower-priority roles stay here.",
      ready_to_apply: "Reviewed resume drafts move here before submission.",
      tailor_resume: "Roles needing resume work collect here."
    },
    stageHelpers: {
      follow_up: "Check whether a note or interview thank-you is due.",
      needs_review: "Decide whether this role deserves your time.",
      parked: "Keep this low priority unless the fit or timeline changes.",
      ready_to_apply: "Do the final keyword check and prepare to submit.",
      tailor_resume: "Finish the targeted summary and project bullets first."
    },
    stages: {
      follow_up: "Follow up",
      needs_review: "Needs review",
      parked: "Parked",
      ready_to_apply: "Ready",
      tailor_resume: "Tailor resume"
    },
    subtitle: "Analyze roles, track opportunities, and plan your next move.",
    trackerSubtitle: "Filters, batch actions, status updates, CSV export, and sync are preserved.",
    trackerTitle: "Opportunity tracker",
    viewTracker: "View tracker",
    workflowGuideToggle: "Workflow Guide",
    actionQueueToggle: "Action Queue",
    activeStages: "active"
  };
}
